// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { SetupAssistant, EvidenceExplanation } from '../src/components/ai-assistance';
import { CustomSetup } from '../src/components/custom-setup';
import { Workspace } from '../src/components/workspace';
import { createExperimentSession } from '../src/lib/experiments/analysis';
import { getExperiment } from '../src/lib/experiments/registry';
import { evidenceContext } from '../src/lib/ai/contracts';

const proposal = { status: 'supported', xColumn: 'Time', yColumn: 'Response', xLabel: 'Time', yLabel: 'Response', xUnit: null, yUnit: null, xUnitEvidence: null, yUnitEvidence: null, modelFamily: 'linear-origin', constantValue: null, constantEvidence: null, rationale: 'A proportional relationship was described.', assumptions: ['Review the reference origin.'], warnings: [] };
const session = createExperimentSession('spring-hooke');
const context = evidenceContext(session.analysis!, session.analysis!.findings.find(f => f.id === 'transition')!, getExperiment('spring-hooke'), 'analysis-a');
const explanation = { findingId: context.findingId, analysisVersion: context.analysisVersion, explanation: 'The residual pattern describes disagreement with the configured model.', whatToInspect: ['Inspect the residual plot.'], caveat: 'Disagreement does not establish a physical cause.' };
const response = (result: unknown) => ({ ok: true, json: async () => ({ result }) });
beforeEach(() => { vi.stubGlobal('requestAnimationFrame', (f: FrameRequestCallback) => { f(0); return 1; }); vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} }); HTMLDialogElement.prototype.showModal = function () { this.open = true; }; HTMLDialogElement.prototype.close = function () { this.open = false; }; });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
function suggest() { fireEvent.change(screen.getByLabelText(/What did you measure/), { target: { value: 'Time against response; expected proportionality.' } }); fireEvent.click(screen.getByRole('button', { name: 'Suggest setup' })); }

it('proposal review requires confirmation and reject does not alter form', async () => { const confirm = vi.fn(); vi.stubGlobal('fetch', vi.fn(async () => response(proposal))); render(<SetupAssistant headers={['Time','Response']} onConfirm={confirm} />); suggest(); await screen.findByText(/AI PROPOSED SETUP/); expect(confirm).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Reject proposal' })); expect(confirm).not.toHaveBeenCalled(); expect(screen.queryByText(/AI PROPOSED SETUP/)).toBeNull(); });
it('confirmation explicitly emits bounded proposal', async () => { const confirm = vi.fn(); vi.stubGlobal('fetch', vi.fn(async () => response(proposal))); render(<SetupAssistant headers={['Time','Response']} onConfirm={confirm} />); suggest(); await screen.findByText(/AI PROPOSED SETUP/); fireEvent.click(screen.getByRole('button', { name: 'Confirm proposal into form' })); expect(confirm).toHaveBeenCalledWith(proposal); });
it('unsupported proposal cannot be confirmed', async () => { vi.stubGlobal('fetch', vi.fn(async () => response({ ...proposal, status: 'unsupported', xColumn: null, yColumn: null, xLabel: null, yLabel: null, modelFamily: null }))); render(<SetupAssistant headers={[]} onConfirm={vi.fn()} />); suggest(); await screen.findByText(/AI PROPOSED SETUP/); expect(screen.queryByRole('button', { name: 'Confirm proposal into form' })).toBeNull(); });
it('description edits discard late suggestions', async () => { let resolve!: (v: unknown) => void; vi.stubGlobal('fetch', vi.fn(() => new Promise(r => { resolve = r; }))); render(<SetupAssistant headers={['Time','Response']} onConfirm={vi.fn()} />); suggest(); fireEvent.change(screen.getByLabelText(/What did you measure/), { target: { value: 'Changed experiment' } }); await act(async () => resolve(response(proposal))); expect(screen.queryByText(/AI PROPOSED SETUP/)).toBeNull(); });
it('no-key failure leaves complete manual setup usable', async () => { vi.stubGlobal('fetch', vi.fn(async () => ({ ok: false, json: async () => ({ error: 'unavailable' }) }))); const analyze = vi.fn(); render(<CustomSetup onAnalyze={analyze} />); suggest(); await screen.findByText(/Configure the experiment manually/); fireEvent.click(screen.getByRole('button', { name: 'Enter manually' })); expect((screen.getByRole('button', { name: '+ Add row' }) as HTMLButtonElement).disabled).toBe(false); expect(analyze).not.toHaveBeenCalled(); });
it('accepted suggestion maps normal configuration but never runs analysis or fills noise', async () => { vi.stubGlobal('fetch', vi.fn(async () => response(proposal))); const analyze = vi.fn(); render(<CustomSetup onAnalyze={analyze} />); fireEvent.change(screen.getByLabelText(/Paste CSV/), { target: { value: 'Time,Response\n1,2\n2,4\n3,6' } }); fireEvent.click(screen.getByRole('button', { name: 'Preview pasted data' })); suggest(); await screen.findByText(/AI PROPOSED SETUP/); expect((screen.getByLabelText('Independent X column') as HTMLSelectElement).value).toBe(''); fireEvent.click(screen.getByRole('button', { name: 'Confirm proposal into form' })); expect((screen.getByLabelText('Independent X column') as HTMLSelectElement).value).toBe('Time'); expect((screen.getByLabelText('Baseline model') as HTMLSelectElement).value).toBe('linear-origin'); expect((screen.getByLabelText(/Assumed response reference scale/) as HTMLInputElement).value).toBe(''); expect(analyze).not.toHaveBeenCalled(); expect((screen.getByRole('button', { name: /Run analysis/ }) as HTMLButtonElement).disabled).toBe(true); });
it('labels explanations and retains deterministic evidence on provider failure', async () => { vi.stubGlobal('fetch', vi.fn(async () => response(explanation))); const view = render(<div><p>Original deterministic finding</p><EvidenceExplanation context={context} /></div>); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); await screen.findByText(/AI EXPLANATION/); expect(screen.getByText('Original deterministic finding')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Dismiss' })); vi.stubGlobal('fetch', vi.fn(async () => { throw new Error('quota'); })); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); await screen.findByText(/temporarily unavailable/); expect(screen.getByText('Original deterministic finding')).toBeTruthy(); view.unmount(); });
it('rejects stale finding version from provider', async () => { vi.stubGlobal('fetch', vi.fn(async () => response({ ...explanation, analysisVersion: 'old' }))); render(<EvidenceExplanation context={context} />); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); await waitFor(() => expect(screen.getByRole('button', { name: 'Retry explanation' })).toBeTruthy()); expect(screen.queryByText(/AI EXPLANATION/)).toBeNull(); });
it('rerun and switching context discard pending explanation', async () => { let resolve!: (v: unknown) => void; vi.stubGlobal('fetch', vi.fn(() => new Promise(r => { resolve = r; }))); const view = render(<EvidenceExplanation key="old" context={context} />); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); view.rerender(<EvidenceExplanation key="new" context={{ ...context, analysisVersion: 'analysis-new' }} />); await act(async () => resolve(response(explanation))); expect(screen.queryByText(/AI EXPLANATION/)).toBeNull(); });
it('changed analysis context rejects a late response even with a reused version', async () => { let resolve!: (v: unknown) => void; vi.stubGlobal('fetch', vi.fn(() => new Promise(r => { resolve = r; }))); const view = render(<EvidenceExplanation context={context} />); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); view.rerender(<EvidenceExplanation context={{ ...context, statistics: { ...context.statistics, 'Criterion improvement': 0 } }} />); await act(async () => resolve(response(explanation))); expect(screen.queryByText(/AI EXPLANATION/)).toBeNull(); });
it('sends only description and headers for setup', async () => { const fetch = vi.fn(async (url: string, init: RequestInit) => { expect(url).toBe('/api/ai/setup'); expect(init.method).toBe('POST'); return response(proposal); }); vi.stubGlobal('fetch', fetch); render(<SetupAssistant headers={['Time','Response']} onConfirm={vi.fn()} />); suggest(); await screen.findByText(/AI PROPOSED SETUP/); expect(Object.keys(JSON.parse(String(fetch.mock.calls[0][1].body))).sort()).toEqual(['description', 'headers']); });
it('sends only selected minimal finding context for explanation', async () => { const fetch = vi.fn(async (url: string, init: RequestInit) => { expect(url).toBe('/api/ai/explain'); expect(init.method).toBe('POST'); return response(explanation); }); vi.stubGlobal('fetch', fetch); render(<EvidenceExplanation context={context} />); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); await screen.findByText(/AI EXPLANATION/); expect(Object.keys(JSON.parse(String(fetch.mock.calls[0][1].body))).sort()).toEqual(['analysisVersion', 'context', 'findingId']); });
it('workspace edit and switch remove old explanations while leaving analysis functional', async () => { vi.stubGlobal('fetch', vi.fn(async (_url, init) => { const input = JSON.parse(init.body); return response({ ...explanation, findingId: input.findingId, analysisVersion: input.analysisVersion }); })); render(<Workspace />); fireEvent.click(screen.getAllByRole('button', { name: /Run analysis/ })[0]); fireEvent.click(screen.getByRole('button', { name: /View full evidence/ })); fireEvent.click(screen.getByRole('button', { name: 'Explain evidence' })); await screen.findByText(/AI EXPLANATION/); fireEvent.click(screen.getByRole('button', { name: 'Close evidence' })); fireEvent.click(screen.getByRole('button', { name: /Open data/ })); fireEvent.change(screen.getByLabelText(/M01 force/), { target: { value: '0.4' } }); expect(screen.queryByText(/AI EXPLANATION/)).toBeNull(); fireEvent.click(screen.getAllByRole('button', { name: /Run analysis/ })[0]); fireEvent.click(screen.getByRole('button', { name: /View full evidence/ })); expect(screen.getByText('DETECTED BY MODELSCOPE')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Close evidence' })); fireEvent.change(screen.getByLabelText('EXPERIMENT'), { target: { value: 'custom' } }); expect(screen.queryByText(/AI EXPLANATION/)).toBeNull(); expect(screen.getByLabelText(/Paste CSV/)).toBeTruthy(); });
