import Link from 'next/link';
import { SiteNav, SiteFooter } from '@/components/site-nav';
import { MethodologyDemo } from '@/components/methodology-demo';
export const metadata = { title: 'How ModelScope decides · Methodology' };
const steps = [
  ['Fit the baseline', 'Use the configured line or fixed theoretical reference. Compare the same observations.', 'M8 44L84 8', 'baseline'],
  ['Compute residuals', 'Observed minus predicted. Structure matters more than a high R².', 'M8 30L24 28L40 32L56 18L72 12L84 8', 'residual'],
  ['Search candidate transitions', 'Compare a continuous hinge at eligible measured inputs. Penalize complexity and the search.', 'M8 44L46 28L84 8', 'search'],
  ['Require sustained deviation', 'At least four consecutive post-knee residuals of one sign must exceed twice the reference scale.', 'M8 30L24 30L40 29L56 18L72 12L84 8', 'persistence'],
  ['Check influence', 'Diagnostically omit the largest absolute baseline residual. Support and departure direction must remain.', 'M8 30L24 29L40 31L56 8L72 29L84 30', 'influence'],
  ['Return the evidence', 'Supported, ambiguous or none. Insufficient sampling is reported separately; no causal claim is made.', 'M8 30L84 30', 'decision'],
];
export default function MethodologyPage() {
  return <main className="home methodology-page"><a className="skip-link" href="#method-content">Skip to methodology</a><SiteNav page="methodology" /><section className="method-overview" id="method-content"><div className="method-intro"><span className="home-kicker">Transparent by design</span><h1>How ModelScope<br />decides.</h1><p>A statistical comparison with explicit safeguards. Every finding links back to measurements and calculated evidence.</p><a className="home-button light" href="https://github.com/luiscontrerasus-glitch/ModelScope/blob/main/docs/methodology.md" target="_blank" rel="noreferrer">Read the full methodology <span aria-hidden="true">↗</span></a></div><ol className="method-steps">{steps.map(([title, copy, path, kind], i) => <li key={title}><span className="step-number">0{i + 1}</span><div><h2>{title}</h2><p>{copy}</p></div><svg viewBox="0 0 92 54" aria-hidden="true"><path d="M8 46H86" stroke="#dce2ea" /><path d={path} stroke={i === 3 || i === 4 ? '#b58149' : '#2378e8'} strokeWidth="1.5" fill="none" />{kind === 'search' && <rect x="40" y="4" width="12" height="43" fill="#2378e818" />}{[12, 28, 44, 60, 76].map((x, j) => <circle key={x} cx={x} cy={kind === 'baseline' ? 44 - j * 8 : 30} r="2.3" fill="#2378e8" />)}</svg></li>)}</ol></section><section className="method-challenge" aria-labelledby="challenge-heading"><span className="home-kicker">Three small challenges</span><h2 id="challenge-heading">Try to fool ModelScope.</h2><p className="method-challenge-intro">An unusual point, ordinary noise, or a sustained departure. The same detector handles each case.</p><MethodologyDemo /></section><section className="method-limits"><div><h2>Evidence has limits.</h2><p>A supported candidate describes statistical disagreement. Its sensitivity range is not a confidence interval, physical failure point, or safe operating boundary.</p></div><div><p>Assume accurate inputs, adequate sampling, an explicit response scale and one possible transition. These demonstrations use synthetic data.</p><Link className="home-button" href="/workspace?experiment=spring-hooke">Inspect a complete analysis <span aria-hidden="true">→</span></Link></div></section><SiteFooter /></main>;
}
