import Link from 'next/link';
import { SiteNav, SiteFooter } from './site-nav';
import { ModelReality } from './model-reality';
import { ConceptPlot } from './concept-plot';
export default function Home() {
  return <main className="home refined-home"><a className="skip-link" href="#home-content">Skip to content</a><SiteNav page="home" />
    <section className="reality-hero" id="home-content" aria-labelledby="hero-heading"><div className="hero-copy"><h1 id="hero-heading">Equations<br />have limits.<br /><span>Find them.</span></h1><p>ModelScope reveals where experimental measurements begin systematically disagreeing with a scientific model.</p><div className="home-actions"><Link className="home-button" href="/explore">Explore Models <span aria-hidden="true">→</span></Link><Link className="home-button light" href="/workspace?experiment=custom">Analyze Your Data</Link></div></div><ModelReality /></section>
    <section className="home-explore-teaser" aria-labelledby="teasers-heading"><div><span className="home-kicker">Explore</span><h2 id="teasers-heading">Four systems.<br />One question.</h2></div><div><p>See how the same idea appears across mechanics, physics, chemistry, and instrumentation.</p><p className="teaser-system-names">Spring <span aria-hidden="true">·</span> Pendulum <span aria-hidden="true">·</span> Beer–Lambert <span aria-hidden="true">·</span> Sensor</p><Link className="teaser-cta" href="/explore">Explore Models <span aria-hidden="true">→</span></Link></div></section>
    <section className="home-thesis" aria-labelledby="thesis-heading"><div><span className="home-kicker">The bigger picture</span><h2 id="thesis-heading">The model looks right.<br />Until it doesn’t.</h2><p>Scientific equations are approximations. ModelScope makes their disagreement with measurements visible.</p><Link className="home-button light" href="/workspace?experiment=spring-hooke">Inspect the evidence <span aria-hidden="true">→</span></Link></div><ConceptPlot /></section>
    <section className="home-architecture" aria-labelledby="architecture-heading"><span className="home-kicker">Under the surface</span><h2 id="architecture-heading">Deterministic science.<br /><span>Optional AI.</span></h2><div className="architecture-flow"><div><span>01</span><h3>Your data</h3><p>CSV, pasted tables<br />or manual measurements</p></div><div><span>02</span><h3>Analysis engine</h3><p>Regression · residuals<br />Segmented comparison<br />Influence safeguards</p></div><div><span>03</span><h3>Evidence</h3><p>Model disagreement<br />Sensitivity ranges<br />Linked observations</p></div><div><span>04 / OPTIONAL</span><h3>AI</h3><p>Setup interpretation<br />Evidence explanation</p></div></div><p className="architecture-statement">AI explains. The analysis engine decides.</p><p className="architecture-privacy">Calculations stay in your browser. Optional AI sends only requested setup or evidence context to the provider, never the full raw dataset.</p><Link className="home-button" href="/workspace?experiment=custom">Start an analysis <span aria-hidden="true">→</span></Link></section><SiteFooter />
  </main>;
}
